### ISSUE TITLE
No "water" 

### ISSUE THREAD

**Issue by Lolicon-Mindustry** [BurritoAlpaca/MindustryPlus#12]
Current version 104.4
![Screenshot_20200302-225535](https://user-images.githubusercontent.com/59752736/75717256-70e5fa00-5cd9-11ea-8e0d-edd37582a39a.jpg)

**Comment by Lolicon-Mindustry** [comment]
Device: HUAWEI MediaPad T5
Android 8.0
Idk you needs this information or no

**Comment by BurritoAlpaca** [comment]
Thanks, have fixed the problem. I wasn't able to test the patch when I uploaded it as I was in a rush, hope you have fun.
